name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        
      - name: Set Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run install
        run: bun install

      - name: Compile contracts
        run: bun compile

      - name: Test hardhat only
        run: bun test:hardhat

      - name: Test forge only
        run: bun test:forge
        
      # New step for gas snapshot checking
      - name: Check gas snapshots
        run: forge snapshot --check
