name: CI
on: [push]
# Environment variables
env:
  MNEMONIC: ${{ secrets.MNEMONIC }}
  INFURA_API_KEY: ${{ vars.INFURA_API_KEY }}
  COINMARKETCAP_API_KEY: ${{ vars.COINMARKETCAP_API_KEY }}
  ALCHEMY_API_KEY: ${{ vars.ALCHEMY_API_KEY }}
  ETHERSCAN_API_KEY: ${{ vars.ETHERSCAN_API_KEY }}
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.7.0 --activate

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$PATH:$HOME/.foundry/bin"
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          foundryup

      - name: Run install
        run: yarn install

      - name: Compile contracts
        run: yarn compile

      - name: Test hardhat only
        run: yarn test:hardhat

      - name: Test forge only
        run: yarn test:forge